version: 2
jobs:
  build:
    docker:
      - image: golang:1.13-alpine
    working_directory: /app
    steps:
    - checkout
    - run:
        name: Install binary dependencies
        command: apk add --update --upgrade ca-certificates build-base glib-dev vips-dev
    - restore_cache:
        keys:
        - v1-pkg-cache-{{ checksum "go.sum" }}
        - v1-pkg-cache-
    - run:
        name: Install dependencies
        command: go mod download
    - run:
        name: Run tests
        command: go test -v ./...
    - save_cache:
        key: v1-pkg-cache-{{ checksum "go.sum" }}
        paths:
        - '/go/pkg'
