name: Go Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install binary dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -y libvips-dev libglib2.0-dev build-essential

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download
        go mod verify

    - name: Test
      run: go test -v ./...
